---
title: "P8105: Data Science I"
author: "Assignment 5<br>Jimmy Kelliher (UNI: jmk2303)"
output:
  github_document:
    toc: TRUE
---

<!------------------------------------------------------------------------------
Preamble
------------------------------------------------------------------------------->

```{r, echo = FALSE, message = FALSE, warning = FALSE}
# load necessary packages
library(tidyverse)

# set knitr defaults
knitr::opts_chunk$set(
    echo      = TRUE
  , message   = FALSE
  , fig.width = 6
  , fig.asp   = .6
  , out.width = "90%"
)

# set theme defaults
theme_set(
  theme_bw() +
  theme(
    legend.position = "bottom"
    , plot.title    = element_text(hjust = 0.5)
    , plot.subtitle = element_text(hjust = 0.5)    
    , plot.caption  = element_text(hjust = 0.0)
  )
)

# set color scale defaults
options(
    ggplot2.continuous.colour = "viridis"
  , ggplot2.continuous.fill   = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete   = scale_fill_viridis_d
```

<!------------------------------------------------------------------------------
Problem 1
------------------------------------------------------------------------------->





<!------------------------------------------------------------------------------
Problem 2
------------------------------------------------------------------------------->

# Problem 2

```{r}
# create tidy dataset for longitudinal study
longData <-
  # create data frame with file names
  tibble(files = list.files("datasets/longitudinal_study")) %>%
  # add a column where each row contains the contents of the corresponding file
  mutate(raw_data = map(
      .x = files
    , ~read_csv(paste0("datasets/longitudinal_study/", .x))
  )) %>%
  # unnest the nested data frames to create an un-tidied, but usable data frame
  unnest(cols = raw_data) %>%
  # pivot longer via week number
  pivot_longer(
      cols         = starts_with("week_")
    , names_to     = "week"
    , names_prefix = "week_"
  ) %>%
  # separate file name into arm type and subject id; use sensible classes
  mutate(
      arm        = factor(recode(
        substr(files, 1, 3)
      , con = "Control"
      , exp = "Experimental"
    ))
    , subject_id = as.integer(substr(files, 5, 6))
    , week       = as.integer(week)
  ) %>%
  # remove file name column now that it is redundant
  select(  arm, subject_id, week, value) %>%
  # relocate columns by group hierarchy
  relocate(arm, subject_id, week, value)

# output tidied dataset
head(longData, 10) %>% knitr::kable()
```

```{r}
# create a spaghetti chart of the data
longData %>%
  # instantiate plot
  ggplot(aes(x = week, y = value, group = subject_id)) +
  # add lines
  geom_line() +
  # create separate line charts for each arm
  facet_grid(~arm) +
  # add meta-data
  labs(
      title = "Value over Time, by Arm"
    , x     = "Week"
    , y     = "Value"
  )
```

<!------------------------------------------------------------------------------
Problem 3
------------------------------------------------------------------------------->

# Problem 3

```{r}
# set seed
set.seed(10)

# edit dataset to introduce missing values
irisMissing <-
  # call dataset
  iris %>% 
  # randomly select 20 entries from each column and assign them missing values
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  # convert Species to a character vector
  mutate(Species = as.character(Species))

# write a function to address missing values
replaceMissing <- function(v) {
  # if input vector v is a numeric vector...
  if (is.numeric(v)) {
    # ... replace missing values with the mean of non-missing values
    replace_na(v, mean(v, na.rm = TRUE))
  # if input vector v is a character vector...
  } else if (is.character(v)) {
    # ... replace missing values with the string "virginica"
    replace_na(v, "virginica")
  }
}

# apply function to each column of edited dataset to fill in missing values
irisCorrected <- map_df(irisMissing, replaceMissing)

# output edited dataset
tail(irisMissing, 10) %>% knitr::kable()

# output corrected dataset
tail(irisCorrected, 10) %>% knitr::kable()
```
